defaults:
  - vdm: config
  - model: bsi/unet

  - ema: ema
  - optimizer: adamw
  - lr_scheduler: warmup

_target_: bsi.tasks.vdm.VDMTraining
_recursive_: no

name: vdm

compile: yes
compile_mode: ~
n_elbo_recon_samples: 1
n_elbo_measure_samples: 1

optimizer:
  lr: 3e-4
  betas: [0.9, 0.99]
  weight_decay: 1e-4
